-- =========================
-- TABLA: productos
-- =========================
CREATE TABLE IF NOT EXISTS public.productos
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(100) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    categoria varchar(50),
    activo boolean NOT NULL DEFAULT true,
    fecha_creacion timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT productos_pkey PRIMARY KEY (id),
    CONSTRAINT productos_precio_check CHECK (precio > 0),
    CONSTRAINT productos_stock_check CHECK (stock >= 0)
);

-- =========================
-- TABLA: orden_detalle
-- =========================
CREATE TABLE IF NOT EXISTS public.orden_detalle
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    CONSTRAINT orden_detalle_pkey PRIMARY KEY (id)
);

-- =========================
-- TABLA: orders
-- =========================
CREATE TABLE IF NOT EXISTS public.orders
(
    id_order integer GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    total numeric(10,2),
    estado varchar(20) DEFAULT 'CREADA',
    fecha timestamp without time zone DEFAULT now(),
    CONSTRAINT orders_pkey PRIMARY KEY (id_order)
);

-- =========================
-- TABLA: usuarios
-- =========================
CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY,
    cedula varchar(10),
    nombre varchar(50),
    correo varchar(100),
    telefono varchar(10),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
);
